### ISSUE TITLE
Example Typescript + LC 39 - Hello World

### ISSUE THREAD

**Issue by TurtleARM** [mia-platform-marketplace/Typescript-LC39-Hello-World-Example#1]

**Comment by fredmaggiowski** [comment]
- [ ] There's no package.json and package-lock.json in the repo
- [ ] Dockerfile is missing a step for typescript transpile
- [ ] [tsconfig](https://github.com/mia-platform-marketplace/Typescript-LC39-Hello-World-Example/blob/master/tsconfig.json#L5) should output transpiled app in `dist` directory
- [ ] rename [transpile script](https://github.com/mia-platform-marketplace/Typescript-LC39-Hello-World-Example/blob/master/package.json#L18) from `typescript` to `build`
- [ ] [name](https://github.com/mia-platform-marketplace/Typescript-LC39-Hello-World-Example/blob/master/package.json#L2) in package.json should be interpolated
- [ ] [repository](https://github.com/mia-platform-marketplace/Typescript-LC39-Hello-World-Example/blob/master/package.json#L20) field in package.json should be deleted
- [ ] [dockerfile](https://github.com/mia-platform-marketplace/Typescript-LC39-Hello-World-Example/blob/master/Dockerfile#L34) should copy only dist from build-dir
- [ ] [index.ts](https://github.com/mia-platform-marketplace/Typescript-LC39-Hello-World-Example/blob/master/src/index.ts#L47) should use CustomService type and avoid the usage of arrow functions
- [ ] Let's check if it's a common practice to have tests in javascript in typescript repositories

**Comment by TurtleARM** [comment]
> * [x]  [name](https://github.com/mia-platform-marketplace/Typescript-LC39-Hello-World-Example/blob/master/package.json#L2) in package.json should be interpolated
Is this name "mia_template_service_name_placeholder" correct?

> * [ ]  Let's check if it's a common practice to have tests in javascript in typescript repositories
Tap doesn't seem to be portable to Typescript

> * [ ]  the repo is identified as `JavaScript` by GitHub in the repository list
Github assigns the language based on the max percentage of code in a certain language, should I force it to Typescript?

> * [ ]  dependabot should be configured to run CI and automerge of minor/patch updates
Dependabot only checks for updates on master, pull request needs to be merged

**Comment by fredmaggiowski** [comment]
As for Typescript in tests we could use `jest` please check if it's feasible to convert current test suites to jest.

For Github displayed language, let's wait whether after tests updates it will recognise it as Typescript otherwise it's better to force it (it'd be bad to have a "Typescript Example" that's flagged as Javascript 😅 

As for dependabot I've just configured to allow it to automerge its PRs so it should be alright, we have to wait until tomorrow for it to open new PRs
